name: 基础镜像

on:
  push:
    branches:
      - 'main'
    paths:
      - 'base/Dockerfile'
      - '.github/workflows/base.yml'
env:
  REGISTRY: docker.io


jobs:
  push_to_registry:
    name: 编译 基础镜像 推送 DockerHub 
    runs-on: ubuntu-latest

    steps:
      - name: 检出当前代码
        uses: actions/checkout@v3

      - name: 登录到${{ env.REGISTRY }}镜像服务
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: 获取时间
        run: echo "TRIGGER_TIME=$(TZ=':Asia/Shanghai' date '+%Y%m%d%H%M')" >> $GITHUB_ENV

      - name: 构建镜像并推送到${{ env.REGISTRY }}镜像仓库
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./base
          push: true
          # platforms: linux/amd64,linux/arm64,linux/arm/v7
          platforms: linux/amd64
          tags: |
            eclairkk/base:${{ env.TRIGGER_TIME }}
            eclairkk/base:latest
