name: 基础镜像

on:
  push:
    branches:
      - 'master'
    paths:
      - 'base'

jobs:
  push_to_registry:
    name: 编译 基础镜像 推送 DockerHub 
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 登录docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          registry: docker.io

      - name: 设置 Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: 获取时间
        run: echo "TRIGGER_TIME=$(TZ=':Asia/Shanghai' date '+%Y%m%d%H%M')" >> $GITHUB_ENV

      - name: 编译镜像
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: base
          push: true
          # platforms: linux/amd64,linux/arm64,linux/arm/v7
          platforms: linux/amd64
          tags: |
            eclairkk/base:${{ env.TRIGGER_TIME }}
            eclairkk/base:latest
