name: 基础镜像

on:
  push:
    branches:
      - 'main'
    paths:
      - 'base/Dockerfile'
      - '.github/workflows/base.yml'
env:
  REGISTRY: docker.io


jobs:
  push_to_registry:
    name: 编译 基础镜像 推送 DockerHub 
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v3

      - name: 登录到${{ env.REGISTRY }}镜像服务
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: 获取触发时间
        id: trigger_time
        run: echo "::set-output name=trigger_time::$(TZ=':Asia/Shanghai' date '+%Y%m%d%H%M')"
        # run: echo "TRIGGER_TIME=$(TZ=':Asia/Shanghai' date '+%Y%m%d%H%M')" >> $GITHUB_ENV

      - name: 构建镜像并推送到${{ env.REGISTRY }}镜像仓库
        uses: docker/build-push-action@v3
        with:
          context: ./base
          push: true
          platforms: linux/amd64
          tags: |
            eclairkk/base:${{ steps.trigger_time.outputs.trigger_time }}
            eclairkk/base:latest
